### ISSUE TITLE
StrataJS.org is written for users who are already sold on it

### ISSUE THREAD

**Issue by ssokolow** [mjackson/strata#10]
When I arrived on StrataJS.org, my first question was "Someone mentioned Strata as WSGI-like. How is that different from things I already know about and why should I use it instead?"

Generally, it's a good idea to either treat the root page of a project's site as the billboard for selling potential developers on the project or provide a clearly obvious "About" link to one that does. (Which, in the case something like Strata (a library that's not first on the scene), means a high-level description of what advantages it offers and, ideally, code snippets clearly demonstrating how Strata makes a developer's life simpler. Probably on a different page linked from the front page, given how you've laid out the site.)

Given how the site's set up now, if I weren't looking for an excuse to to procrastinate a little coursework, I'd probably have just dismissed it and stuck with something Express-based for my planned projects.

If nothing else, could you at least add a pullquote of the "The main advantage that Strata has over the Connect/Express library is that..." paragraph from the readme file?

**Comment by mjackson** [comment]
I'm working on it. :) The way I see it, code quality and documentation should always come before a pretty website. If I were to do it in the reverse order, I'd have re-invented Express.

**Comment by ssokolow** [comment]
True, but it's generally a good idea for first-impression's sake to delay your public launch for the 5 to 15 minutes necessary to at least put up a description of what you _intend_ to do differently.

The big benefit to "release early, release often" is that you can start getting feedback and building a community early... and being clear about what makes you project special really helps there.

**Comment by mjackson** [comment]
I completely agree, but I think you may underestimate the amount of effort it takes to fully explain to the kind of users who are going to judge your project based on its website the differences between the two projects. The major differences are much deeper than syntax. Hence, little code snippets may not do much to urge users to make the switch.

I do agree with what you're saying though, and I'm in the process of trying to make updates and improvements to the code and educate the budding community all at once. It's a lot to do for one person in his spare time. Would love a little help if you're up for it.

**Comment by ssokolow** [comment]
Fair enough. I was actually thinking more about the importance of at least having a narrative-form summary when I said 5 to 15 minutes. (Sort of like how, with a desktop or terminal app, there's no excuse to not take at least _one_ screenshot if you're going to the effort to put it up for people to stumble across)

As for help, at the moment, I just finished spending a week getting significantly behind in my coursework while I completely renovated two of my own sites, but once I get a caught back up on my life (Warning: could potentially take a while), I can give it a shot.

**Comment by ssokolow** [comment]
I don't think I'll be able to help.

I just spent roughly a month recovering from my main PC going bad and now it's looking like I'll be two months behind on life because I didn't have adequate backup plans for ensuring the tools I needed would be available on my backup PC. (So I've got a month of backlogged TODOs and stuff to organize)
