### ISSUE TITLE
Show how to set up a web proxy

### ISSUE THREAD

**Issue by marktorrance** [mjackson/strata#12]
I'm interested in using Node as a proxy to an existing web app for most of my CRUD stuff (written in Rails), but I want to let Node do some websockets stuff for particular URLs.  Is Strata a good choice for this?  If so, how can I get access to the raw request to upgrade the socket to use socket.io, and to pass the parameters through to the downstream web app when I choose to be a proxy?

**Comment by mjackson** [comment]
At this time I wouldn't recommend using Strata for a web proxy. The current goal of the library is to serve as a web framework. It may expand in the future, but that's it for now.
