### ISSUE TITLE
Can you recommend a Restful API generator that works with strata

### ISSUE THREAD

**Issue by digitalrinaldo** [mjackson/strata#13]
I would like to be able ot use strata and have some of that repetitive work done for me. I have looked at several projects already and I am not sure why Id on't get it. They often seem to be separate servers. 

Rinaldo

**Comment by mjackson** [comment]
Strata is a very young project at the moment, so I don't believe any such thing exists yet. It shouldn't be too difficult to write a simple API by hand though. See the "Advanced Routing" example in [the user manual](http://stratajs.org/manual) for some ideas of how to do this.
