### ISSUE TITLE
Unable to install strata

### ISSUE THREAD

**Issue by murtaza52** [mjackson/strata#14]
Hi,

I wanted to try out strata and its giving an error when I tried installing through npm. Could someone please help? Below is the error log.

Thanks,
Murtaza

npm install strata
npm ERR! Error: Not found: strata@''
npm ERR! Valid install targets:
npm ERR! ["latest"]
npm ERR!     at installTargetsError (/home/murtaza/.nvm/v0.5.9/lib/node_modules/np
npm ERR!     at /home/murtaza/.nvm/v0.5.9/lib/node_modules/npm/lib/cache.js:403:17
npm ERR!     at saved (/home/murtaza/.nvm/v0.5.9/lib/node_modules/npm/lib/utils/np
npm ERR!     at Object.cb [as oncomplete](/home/murtaza/.nvm/v0.5.9/lib/node_modu)
npm ERR! Report this _entire_ log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com
npm ERR! 
npm ERR! System Linux 3.0.0-12-generic-pae
npm ERR! command "node" "/home/murtaza/.nvm/v0.5.9/bin/npm" "install" "strata"
npm ERR! cwd /home/murtaza
npm ERR! node -v v0.5.9
npm ERR! npm -v 1.0.101
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/murtaza/npm-debug.log
npm not ok

**Comment by mjackson** [comment]
This error looks like it has something to do with npm, not strata. Could possibly be an nvm error, but I'm not sure.

**Comment by murtaza52** [comment]
Thanks for the quick response. Michael I am however able to install other packages using npm, and dont receive any errors. 

In the meanwhile I will post it to nvm too.

**Comment by mjackson** [comment]
I would report it to npm as it says to do in the error message, not nvm. The error is being thrown from inside cache.js in npm.
