### ISSUE TITLE
Installation fails on node 0.6.x

### ISSUE THREAD

**Issue by ixti** [mjackson/strata#20]
Subj. Because of gzbz2. It has a pull request to fix that issue, but still not merged in. Does this dependency is really important?

These are issues related to gzbz2: Woodya/node-gzbz2#8, Woodya/node-gzbz2#9, Woodya/node-gzbz2#11

**Comment by ixti** [comment]
sorry, accidentally pressed close button

**Comment by mjackson** [comment]
It's only needed for the gzip module on node < 0.6. I think I'll just remove the dependency entirely and tell those who are using old versions of node that they can't use the gzip module unless they upgrade.

**Comment by ixti** [comment]
Thanks in advance.

**Comment by ixti** [comment]
New version works just fine on node >= 0.6
