### ISSUE TITLE
Could you publish latest to npm? (with empty file fix and bufferstream@1.6.0)

### ISSUE THREAD

**Issue by jeffbski** [mjackson/strata#43]
If possible could you bump the version and publish to npm so we can use the latest master fixes without having to point to the github repo.

strata master has the empty file upload fix and the bufferedstream@1.6.0 which is necessary for node 0.10+ support (due to the new process.nextTick change).

Thanks!

Jeff

**Comment by mjackson** [comment]
All done! Version 0.20.1 is out now.

**Comment by jeffbski** [comment]
Excellent! Thanks.
