### ISSUE TITLE
add a paragraph at the very top of the site / user manual saying why strata is cooler/better than express!

### ISSUE THREAD

**Issue by DTrejo** [mjackson/strata#9]
I'd like to read a paragraph like this. Thank you!
D

**Comment by mjackson** [comment]
This is a pretty common request. A lot of web devs are having problems delineating the differences between the two, it seems. I'll add a "Rationale" section to the README.

**Comment by DTrejo** [comment]
Yay!

**Comment by DTrejo** [comment]
Make sure to note that you have concrete and commented examples for many common use cases. I think that counts for something (or more than something).

**Comment by mjackson** [comment]
I've written down some of my thoughts [in this commit](https://github.com/mjijackson/strata/commit/8f4ae27df285e69f4a5abff2e34cbe797fe41322).

**Comment by DTrejo** [comment]
Looks great, thank you for the explanation!
D

On Tue, Oct 4, 2011 at 12:13 PM, Michael Jackson <
reply@reply.github.com>wrote:

> I've written down some of my thoughts [in this commit](https://github.com/mjijackson/strata/commit/8f4ae27df285e69f4a5abff2e34cbe797fe41322).
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/mjijackson/strata/issues/9#issuecomment-2288228

## 

My indie music project, mixest.com
for more projects, dtrejo.com
